version: "3.6"
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wp-content:/var/www/testwp2/wp-content
    environment:
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: "true"
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'http://localhost:8080' );
        define( 'WP_SITEURL', 'http://localhost:8080' );
    depends_on:
      - mariadb
      - phpmyadmin
    restart: always
    ports:
      - 8080:80

  mariadb:
    container_name: mariadb
    image: mariadb:10.8
    ports:
        - 3310:3306
    environment:
      MARIADB_DATABASE: db_name
      MARIADB_USER: db_user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: rootpassword
    restart: always

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
 
volumes:
 db_data:
